name: Blog Notifications
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
    branches:
      - main

jobs:
  send-blog-notifications:
    # Only run if the deployment was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }} # Get the correct commit

      # Check if blog content changed
      - name: Check for blog changes
        id: check_changes
        run: |
          git fetch origin ${{ github.event.workflow_run.head_branch }}
          CHANGED_FILES=$(git diff --name-only ${{ github.event.workflow_run.head_sha }}^ ${{ github.event.workflow_run.head_sha }} | grep "^src/content/blog/")
          if [ -n "$CHANGED_FILES" ]; then
            echo "Blog content changed"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No blog content changes"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        if: steps.check_changes.outputs.has_changes == 'true'
        run: npm install axios xml2js

      - name: Fetch RSS and call API
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Your existing node script here
        env:
          ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
